services:
  traefik:
    container_name: traefik
    image: traefik:v3.3
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.home`)"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      TZ: "Europe/Amsterdam"
      FTLCONF_dns_listeningMode: "all"
    volumes:
      - "/srv/docker/pihole:/etc/pihole"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`pihole.home`)"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
  stirling:
    container_name: stirling
    image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:latest
    volumes:
      - /srv/docker/stirling-pdf/trainingData:/usr/share/tessdata # Required for extra OCR languages
      - /srv/docker/stirling-pdf/extraConfigs:/configs
      - /srv/docker/stirling-pdf/customFiles:/customFiles/
      - /srv/docker/stirling-pdf/logs:/logs/
      - /srv/docker/stirling-pdf/pipeline:/pipeline/
    restart: unless-stopped
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - LANGS=en_GB
      - UI_APP_NAME=Stirling PDF
      - UI_HOME_DESCRIPTION=Your locally hosted one-stop-shop for all your PDF needs.
      - UI_APP_NAVBAR_NAME=Stirling PDF
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stirling.rule=Host(`stirling.home`)"
      - "traefik.http.services.stirling.loadbalancer.server.port=8080"
