services:
  stirling:
    container_name: stirling
    image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:0.45.6
    volumes:
      - /srv/docker/stirling-pdf/trainingData:/usr/share/tessdata # Required for extra OCR languages
      - /srv/docker/stirling-pdf/extraConfigs:/configs
      - /srv/docker/stirling-pdf/customFiles:/customFiles/
      - /srv/docker/stirling-pdf/logs:/logs/
      - /srv/docker/stirling-pdf/pipeline:/pipeline/
    restart: unless-stopped
    networks:
      - homelab
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - LANGS=en_GB
      - UI_APP_NAME=Stirling PDF
      - UI_HOME_DESCRIPTION=Your locally hosted one-stop-shop for all your PDF needs.
      - UI_APP_NAVBAR_NAME=Stirling PDF
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stirling.rule=Host(`stirling.home`)"
      - "traefik.http.services.stirling.loadbalancer.server.port=8080"

networks:
  homelab:
    external: true
